<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-02T15:31:22 IST" name="Suite" finished-at="2024-04-02T15:32:09 IST" duration-ms="46763">
    <groups>
      <group name="regression">
        <method signature="TC_002_Blogcreation.setupblog()[pri:0, instance:Testcases.TC_002_Blogcreation@543295b0]" name="setupblog" class="Testcases.TC_002_Blogcreation"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="TC_002_Blogcreation.setupblog()[pri:0, instance:Testcases.TC_002_Blogcreation@543295b0]" name="setupblog" class="Testcases.TC_002_Blogcreation"/>
      </group> <!-- sanity -->
      <group name="master">
        <method signature="TC_002_Blogcreation.setupblog()[pri:0, instance:Testcases.TC_002_Blogcreation@543295b0]" name="setupblog" class="Testcases.TC_002_Blogcreation"/>
      </group> <!-- master -->
    </groups>
    <test started-at="2024-04-02T15:31:22 IST" name="usercreateTest" finished-at="2024-04-02T15:32:09 IST" duration-ms="46763">
      <class name="Testcases.TC_002_Blogcreation">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:Testcases.TC_002_Blogcreation@543295b0]" started-at="2024-04-02T15:31:22 IST" name="setup" finished-at="2024-04-02T15:31:37 IST" duration-ms="14726" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mac]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="setupblog()[pri:0, instance:Testcases.TC_002_Blogcreation@543295b0]" started-at="2024-04-02T15:31:37 IST" name="setupblog" finished-at="2024-04-02T15:32:09 IST" duration-ms="31435" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at Testcases.TC_002_Blogcreation.setupblog(TC_002_Blogcreation.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupblog -->
      </class> <!-- Testcases.TC_002_Blogcreation -->
    </test> <!-- usercreateTest -->
  </suite> <!-- Suite -->
</testng-results>
